name: Build Blog HTML

on:
  push:
    paths:
      - "posts/**.md"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-posts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install gray-matter marked

      - name: Generate HTML from Markdown
        run: |
          mkdir -p blog-posts
          cat << 'EOF' > build-posts.js
          const fs = require("fs");
          const matter = require("gray-matter");
          const { marked } = require("marked");
          const postsDir = "posts";
          const outputDir = "blog-posts";

          if (!fs.existsSync(postsDir)) process.exit(0);
          if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir);

          const files = fs.readdirSync(postsDir).filter(f => f.endsWith(".md"));
          files.forEach(file => {
            const raw = fs.readFileSync(`${postsDir}/${file}`, "utf8");
            const { data, content } = matter(raw);
            const slug = data.slug || file.replace(/\.md$/, "");
            const htmlContent = marked(content);
            const html = `<!DOCTYPE html>
          <html lang='en'>
          <head>
            <meta charset='UTF-8'>
            <meta name='viewport' content='width=device-width, initial-scale=1.0'>
            <title>${data.title || slug}</title>
            <link rel='stylesheet' href='../style.css'>
          </head>
          <body>
            <h1>${data.title || slug}</h1>
            <article>${htmlContent}</article>
            <p><a href="../blog.html">← Back to Blog</a></p>
          </body>
          </html>`;
            fs.writeFileSync(`${outputDir}/${slug}.html`, html);
            console.log("Generated:", slug + ".html");
          });
          EOF
          node build-posts.js

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main
          git add blog-posts/
          git commit -m "🚀 Auto-generate blog posts HTML" || echo "No changes"
          git push
