name: Build Blog HTML

on:
  push:
    paths:
      - "posts/**.md"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-posts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install gray-matter marked

      - name: Generate HTML from Markdown
        run: |
          mkdir -p blog-posts
          cat << 'EOF' > build-posts.js
          const fs = require("fs");
          const matter = require("gray-matter");
          const { marked } = require("marked");
          const postsDir = "posts";
          const outputDir = "blog-posts";

          if (!fs.existsSync(postsDir)) process.exit(0);
          if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir);

          const files = fs.readdirSync(postsDir).filter(f => f.endsWith(".md"));
          files.forEach(file
