name: Build Blog HTML and posts.json

on:
  push:
    paths:
      - "posts/**.md"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-posts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install gray-matter marked

      - name: Generate blog-posts/ and posts.json
        run: |
          mkdir -p blog-posts
          echo 'const fs = require("fs");
const matter = require("gray-matter");
const { marked } = require("marked");

const postsDir = "posts";
const outputDir = "blog-posts";
const jsonFile = "posts.json";

if (!fs.existsSync(postsDir)) process.exit(0);
if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir);

const posts = [];

const files = fs.readdirSync(postsDir).filter(f => f.endsWith(".md"));
files.forEach(file => {
  const raw = fs.readFileSync(`${postsDir}/${file}`, "utf8");
  const { data, content } = matter(raw);
  const slug = data.slug || file.replace(/\.md$/, "");
  const htmlContent = marked(content);

  // Create HTML
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${data.title || slug}</title>
  <link rel="stylesheet" href="../style.css">
</head>
<body>
  <h1>${data.title || slug}</h1>
  <article>${htmlContent}</article>
  <p><a href="../blog.html">← Back to Blog</a></p>
</body>
</html>`;
  fs.writeFileSync(`${outputDir}/${slug}.html`, html);
  console.log("Generated:", slug + ".html");

  // Add to JSON list
  posts.push({
    title: data.title || slug,
    slug: slug,
    date: data.date || null,
    summary: data.summary || "",
    cover: data.cover || ""
  });
});

// Sort by date desc if available
posts.sort((a, b) => new Date(b.date) - new Date(a.date));
fs.writeFileSync(jsonFile, JSON.stringify(posts, null, 2));
' > build-posts.js

          node build-posts.js

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add blog-posts/ posts.json
          git diff --cached --quiet || git commit -m "🤖 Auto-generate blog-posts and posts.json"
          git pull --rebase origin main || true
          git push
